<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Collecting\Api\Representation\CollectingItemRepresentation $cItem
 */

$translate = $this->plugin('translate');

$userName = $cItem->collectingUser() && $cItem->collectingUser()->user() && $cItem->collectingUser()->user()->name() ? $cItem->collectingUser()->user()->name() : $cItem->userName();
if (null === $userName || $cItem->anon() || 'private' === $cItem->form()->anonType()) {
    // Must set anonymous user, even when the current user has permission, so
    // the citation remains safe to cut-and-paste.
    $userName = $translate('[anonymous user]');
}
?>

<?php echo sprintf(
    $translate('This item was submitted on %s by %s using the form “%s” on the site “%s”: %s'),
    $this->i18n()->dateFormat($cItem->item()->created(), 'long'),
    $userName,
    $cItem->form()->label(),
    $cItem->form()->site()->title(),
    $cItem->form()->site()->siteUrl(null, true)
); ?>
