<?php
echo $this->pageTitle(sprintf($this->translate('Collecting Form: “%s”'), $cForm->label()));
$description = $cForm->description() ?: $this->translate('[none]');
$itemSetLabel = $cForm->itemSet()
    ? $cForm->itemSet()->displayTitle()
    : $this->translate('[none]');
?>

<div id="page-actions">
    <?php if ($cForm->userIsAllowed('update')): ?>
    <?php echo $cForm->link($this->translate('Edit form'), 'edit', ['class' => 'button']); ?>
    <?php endif; ?>
</div>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<div class="property">
    <h4><?php echo $this->translate('Label'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($cForm->label()); ?></div>
</div>

<div class="property">
    <h4><?php echo $this->translate('Description'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($description); ?></div>
</div>

<div class="property">
    <h4><?php echo $this->translate('Item Set'); ?></h4>
    <div class="value"><?php echo $this->escapeHtml($itemSetLabel); ?></div>
</div>

<br>
<h3><?php echo $this->translate('Prompts'); ?></h3>

<?php if ($prompts = $cForm->prompts()): ?>

<table class="tablesaw">
    <thead>
    <tr>
        <th><?php echo $this->translate('Type'); ?></th>
        <th><?php echo $this->translate('Text'); ?></th>
        <th><?php echo $this->translate('Required?'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($prompts as $prompt): ?>
    <?php
    $typeField = $this->collecting()->typeValue($prompt->type());
    if ('property' === $prompt->type()) {
        $typeField = sprintf('%s [%s]', $typeField, $prompt->property()->term());
    } elseif ('media' === $prompt->type()) {
        $typeField = sprintf('%s [%s]', $typeField, $this->collecting()->mediaTypeValue($prompt->mediaType()));
    }
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($typeField); ?></td>
        <td><?php echo $this->escapeHtml($prompt->text()); ?></td>
        <td><?php echo $prompt->required() ? $this->translate('Yes') : $this->translate('No'); ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

<p><?php echo $this->translate('This form has no prompts.'); ?></p>

<?php endif; ?>
