<?php
$this->headScript()->appendFile($this->assetUrl('js/sortable.js', 'Omeka'));
echo $this->pageTitle('Edit Form: “Share your photo”');
$form->prepare();
?>
<?php echo $this->form()->openTag($form); ?>

<div id="page-actions">
    <a href="#" class="delete button">Delete</a>
    <button>Save</button>
</div>

<?php echo $this->formCollection($form, false); ?>

<h3>Prompts</h3>

<?php echo $this->hyperlink('Add Prompt', '#', ['class' => 'button sidebar-content', 'data-sidebar-content-url' => $this->url(null, ['action' => 'add-prompt'], true)]); ?>

<table class="tablesaw">
    <thead>
    <tr>
        <th></th>
        <th>Type</th>
        <th>Text</th>
    </tr>
    </thead>
    <tbody id="prompts">
    <tr class="prompt">
        <td><span class="sortable-handle"></span></td>
        <td>
            Property
            <ul class="actions">
                <li><a href="#" class="sidebar-content o-icon-edit" aria-label="Edit" title="Edit" data-sidebar-content-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'edit-prompt'], true)); ?>"></a></li>
                <li><a href="#" class="o-icon-delete" aria-label="Delete" title="Delete"></a></li>
            </ul>
        </td>
        <td>Give your photo a title</td>
    </tr>
    <tr>
        <td><span class="sortable-handle"></span></td>
        <td>
            Property
            <ul class="actions">
                <li><a href="#" class="o-icon-edit" aria-label="Edit" title="Edit"></a></li>
                <li><a href="#" class="o-icon-delete" aria-label="Delete" title="Delete"></a></li>
            </ul>
        </td>
        <td>Describe your photo</td>
    </tr>
    <tr>
        <td><span class="sortable-handle"></span></td>
        <td>
            Media
            <ul class="actions">
                <li><a href="#" class="o-icon-edit" aria-label="Edit" title="Edit"></a></li>
                <li><a href="#" class="o-icon-delete" aria-label="Delete" title="Delete"></a></li>
            </ul>
        </td>
        <td>Upload your photo here</td>
    </tr>
    <tr>
        <td><span class="sortable-handle"></span></td>
        <td>
            Supplementary
            <ul class="actions">
                <li><a href="#" class="o-icon-edit" aria-label="Edit" title="Edit"></a></li>
                <li><a href="#" class="o-icon-delete" aria-label="Delete" title="Delete"></a></li>
            </ul>
        </td>
        <td>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent luctus
        arcu vel neque suscipit, at aliquam nibh eleifend. Nunc tortor.?</td>
    </tr>
    </tbody>
</table>
<?php echo $this->form()->closeTag(); ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="Close"
        title="Close"></a>
    <div class="sidebar-content"></div>
</div>

<script>
$(document).ready( function() {
    new Sortable(document.getElementById('prompts'), {
        handle: '.sortable-handle'
    });
});
</script>
