<?php
$form->prepare();
$this->headScript()->appendFile($this->assetUrl('js/sortable.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/collecting-form.js', 'Collecting'));

$pageTitle = $isEdit
    ? sprintf($this->translate('Edit Form: “%s”'), $collectingForm->label())
    : $this->translate('Add Form');
$promptsData = $isEdit
    ? json_encode($collectingForm->prompts())
    : '[]';
$promptRowTemplate = <<<EOD
<tr class="prompt">
    <td><span class="sortable-handle"></span></td>
    <td>
        <span class="prompt-type-span"></span>
        <ul class="actions">
            <li><a href="#" class="prompt-edit o-icon-edit" aria-label="Edit" title="Edit"></a></li>
            <li><a href="#" class="prompt-delete o-icon-delete" aria-label="Delete" title="Delete"></a></li>
            <li><a href="#" class="prompt-undo-delete o-icon-undo" aria-label="Undo Delete" title="Undo Delete" style="display: none;"></a></li>
        </ul>
        <input type="hidden" class="prompt-id" name="o-module-collecting:collecting_prompts[__INDEX__][o:id]">
        <input type="hidden" class="prompt-type" name="o-module-collecting:collecting_prompts[__INDEX__][o-module-collecting:type]">
        <input type="hidden" class="prompt-text" name="o-module-collecting:collecting_prompts[__INDEX__][o-module-collecting:text]">
        <input type="hidden" class="prompt-input-type" name="o-module-collecting:collecting_prompts[__INDEX__][o-module-collecting:input_type]">
        <input type="hidden" class="prompt-select-options" name="o-module-collecting:collecting_prompts[__INDEX__][o-module-collecting:select_options]">
        <input type="hidden" class="prompt-media-type" name="o-module-collecting:collecting_prompts[__INDEX__][o-module-collecting:media_type]">
        <input type="hidden" class="prompt-property-id" name="o-module-collecting:collecting_prompts[__INDEX__][o:property][o:id]">
    </td>
    <td><span class="prompt-text-span"></span></td>
</tr>
EOD;

echo $this->pageTitle($pageTitle);
echo $this->form()->openTag($form);
?>

<div id="page-actions">
    <?php if ($isEdit): ?>
    <a href="#" class="sidebar-content delete button" data-sidebar-selector="#delete-confirm-sidebar" data-sidebar-content-url="<?php echo $this->url('admin/site/slug/collecting/id', ['action' => 'delete-confirm', 'id' => $collectingForm->id()], true); ?>">Delete</a>
    <?php endif; ?>
    <button>Save</button>
</div>

<?php echo $this->formCollection($form, false); ?>

<h3>Prompts</h3>

<span id="prompts-span"
    data-prompts-data="<?php echo $this->escapeHtml($promptsData); ?>"
    data-prompt-row-template="<?php echo $this->escapeHtml($promptRowTemplate); ?>"></span>

<a href="#" id="prompt-add" class="button">Add Prompt</a>

<table class="tablesaw">
    <thead>
    <tr>
        <th></th>
        <th>Type</th>
        <th>Text</th>
    </tr>
    </thead>
    <tbody id="prompts"></tbody>
</table>

<?php echo $this->form()->closeTag(); ?>

<div id="prompt-sidebar" class="sidebar">
    <a href="#" class="sidebar-close o-icon-close" aria-label="Close" title="Close"></a>
    <div class="sidebar-content">
        <h3>Prompt</h3>

        <div class="sidebar-section">
            <h4>Prompt Type</h4>
            <select id="prompt-type" name="type">
                <option value="">Select a prompt type...</option>
                <option value="property">Property</option>
                <option value="media">Media</option>
                <option value="input">Supplementary</option>
            </select>
        </div>

        <div class="sidebar-section">
            <h4>Prompt Text</h4>
            <textarea id="prompt-text" name="text" style="width:100%;" rows="3"></textarea>
        </div>

        <div class="sidebar-section">
            <h4>Property</h4>
            <?php echo $this->propertySelect(['name' => 'property', 'options' => ['empty_option' => 'Select a property...'], 'attributes' => ['id' => 'prompt-property']]); ?>
        </div>

        <div class="sidebar-section">
            <h4>Media Type</h4>
            <select id="prompt-media-type" name="media-type">
                <option value="">Select a media type</option>
                <option value="upload">Upload</option>
                <option value="url">URL</option>
                <option value="html">HTML</option>
            </select>
        </div>

        <div class="sidebar-section">
            <h4>Input Type</h4>
            <select id="prompt-input-type" name="input-type">
                <option value="text">Text box (one line)</option>
                <option value="textarea">Text box (multiple line)</option>
                <option value="select">Select menu</option>
            </select>
        </div>

        <div class="sidebar-section">
            <h4>Select Menu Options</h4>
            <textarea id="prompt-select-options" name="select-options" style="width:100%;" rows="3" placeholder="Option One&#13;&#10;Option Two&#13;&#10;..."></textarea>
        </div>

        <a id="prompt-save" href="#" class="button">Save Changes</a>
    </div>
</div>

<div id="delete-confirm-sidebar" class="sidebar">
    <a href="#" class="sidebar-close o-icon-close" aria-label="Close" title="Close"></a>
    <div class="sidebar-content"></div>
</div>
