<?php
echo $this->pageTitle($this->translate('Collecting'));
?>

<div id="page-actions">
    <?php if ($this->userIsAllowed('Collecting\Api\Adapter\CollectingFormAdapter', 'create')): ?>
    <a href="<?php echo $this->url('admin/site/slug/collecting/default', ['action' => 'add'], true); ?>" class="button"><?php echo $this->translate('Add new form'); ?></a>
    <?php endif; ?>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<table class="tablesaw">
    <thead>
    <tr>
        <th><?php echo $this->translate('Label'); ?></th>
        <th><?php echo $this->translate('Owner'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($cForms as $cForm): ?>
    <?php
    $owner = $cForm->owner();
    $ownerName = $owner ? $owner->name() : null;
    ?>
    <tr>
        <td>
            <?php echo $cForm->link($cForm->label(), 'show'); ?>
            <ul class="actions">
                <?php if ($cForm->userIsAllowed('update')): ?>
                <li><a href="<?php echo $this->url('admin/site/slug/collecting/id', ['action' => 'edit', 'id' => $cForm->id()], true); ?>" class="o-icon-edit" aria-label="<?php echo $this->translate('Edit'); ?>" title="<?php echo $this->translate('Edit'); ?>"></a></li>
                <?php endif; ?>
                <?php if ($cForm->userIsAllowed('delete')): ?>
                <li><a href="#" class="sidebar-content o-icon-delete" aria-label="<?php echo $this->translate('Delete'); ?>" title="<?php echo $this->translate('Delete'); ?>" data-sidebar-content-url="<?php echo $this->url('admin/site/slug/collecting/id', ['action' => 'delete-confirm', 'id' => $cForm->id()], true); ?>"></a></li>
                <?php endif; ?>
            </ul>
        </td>
        <td><?php echo $ownerName; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#" class="sidebar-close o-icon-close" aria-label="<?php echo $this->translate('Close'); ?>" title="<?php echo $this->translate('Close'); ?>"></a>
    <div class="sidebar-content"></div>
</div>
