<?php
echo $this->pageTitle('Collecting');
?>

<div id="page-actions">
    <a href="<?php echo $this->url('admin/site/slug/collecting/default', ['action' => 'add'], true); ?>" class="button">Add new form</a>
</div>
<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<table class="tablesaw">
    <thead>
    <tr>
        <th>Label</th>
        <th>Owner</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($collectingForms as $collectingForm): ?>
    <?php
    $owner = $collectingForm->owner();
    $ownerName = $owner ? $owner->name() : null;
    ?>
    <tr>
        <td>
            <?php echo $collectingForm->label(); ?>
            <ul class="actions">
                <li><a href="<?php echo $this->url('admin/site/slug/collecting/id', ['action' => 'edit', 'id' => $collectingForm->id()], true); ?>" class="o-icon-edit" aria-label="Edit" title="Edit"></a></li>
                <li><a href="#" class="sidebar-content o-icon-delete" aria-label="Delete" title="Delete" data-sidebar-content-url="<?php echo $this->url('admin/site/slug/collecting/id', ['action' => 'delete-confirm', 'id' => $collectingForm->id()], true); ?>"></a></li>
            </ul>
        </td>
        <td><?php echo $ownerName; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div class="sidebar">
    <a href="#" class="sidebar-close o-icon-close" aria-label="Close" title="Close"></a>
    <div class="sidebar-content"></div>
</div>

<script>
$(document).ready(function() {



});
