<?php
$this->htmlElement('body')->appendAttribute('class', 'browse');
echo $this->pageTitle(sprintf($this->translate('Collecting Form: “%s”'), $cForm->label()));
?>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<?php if ($cItems): ?>

<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th>Title</th>
        <th>User</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($cItems as $cItem): ?>
    <?php
    if ($user = $cItem->collectingUser()->user()) {
        $userText = $user->link($user->name());
    } else {
        $userText = $this->translate('[anonymous]');
    }
    ?>
    <tr>
        <td>
        <?php if ($media = $cItem->item()->primaryMedia()): ?>
        <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>" style="width:2.25em;">
        <?php endif; ?>
        <?php echo $cItem->link($cItem->item()->displayTitle()); ?>
        </td>
        <td><?php echo $userText; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php else: ?>

<p><?php echo $this->translate('This form has no collected items.'); ?></p>

<?php endif; ?>
