<?php
echo $this->pageTitle(sprintf($this->translate('Collecting Form: “%s”'), $cForm->label()));
?>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<?php if ($cItems): ?>

<?php foreach ($cItems as $cItem): ?>
<?php $item = $cItem->item(); ?>
<div>
    <h3>
        <?php if ($media = $item->primaryMedia()): ?>
        <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>" style="width:2.25em;">
        <?php endif; ?>
        <?php echo $item->displayTitle(); ?>
    </h3>
    <p><a href="<?php echo $this->escapeHtml($item->url()); ?>" class="button">View item</a> <a href="" class="button">View details</a></p>

    <?php if ($inputs = $cItem->inputs()): ?>

    <table class="tablesaw">
        <thead>
        <tr>
            <th>Prompt</th>
            <th>User Input</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($inputs as $input): ?>
        <?php
        $prompt = $input->prompt();
        $promptText = $input->prompt()->text();
        if (!$promptText && 'property' === $prompt->type()) {
            $promptText = $prompt->property()->label();
        }
        $userText = substr($input->text(), 0, 100);
        ?>
        <tr>
            <td><?php echo $this->escapeHtml($promptText); ?></td>
            <td><?php echo $this->escapeHtml($userText); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php endif; ?>

</div>
<?php endforeach; ?>

<?php else: ?>

<p><?php echo $this->translate('This form has no collected items.'); ?></p>

<?php endif; ?>
