<?php
echo $this->pageTitle(sprintf($this->translate('Collecting Form: “%s”'), $cForm->label()));
?>

<nav class="section-nav">
    <?php echo $this->navigation('Zend\Navigation\Collecting')->menu(); ?>
</nav>

<h3><?php echo sprintf($this->translate('Collecting Item: “%s”'), $cItem->item()->displayTitle()); ?></h3>

<?php echo $cItem->item()->link('View item', null, ['class' => 'button']); ?>

<?php if ($media = $cItem->item()->primaryMedia()): ?>
<img src="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>">
<?php endif; ?>

<?php if ($inputs = $cItem->inputs()): ?>

<table class="browse tablesaw" data-tablesaw-mode="stack">
    <thead>
    <tr>
        <th><?php echo $this->translate('Prompt'); ?></th>
        <th><?php echo $this->translate('User Input'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($inputs as $input): ?>
    <?php
    $promptField = $input->prompt()->text();
    if (!$promptField && 'property' === $input->prompt()->type()) {
        $promptField = $input->prompt()->property()->label();
    }
    $userInputField = substr($input->text(), 0, 100);
    ?>
    <tr>
        <td><?php echo $this->escapeHtml($promptField); ?></td>
        <td><?php echo $this->escapeHtml($userInputField); ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>
