<div class="resource-details">
    <h3><?php echo $cItem->item()->displayTitle(); ?></h3>
    <div class="meta-group">
        <h4><?php echo $this->translate('Media'); ?></h4>
        <?php foreach ($cItem->item()->media() as $media): ?>
        <div class="value">
            <a href="<?php echo $media->url(); ?>" target="_blank">
                <img src="<?php echo $this->escapeHtml($media->thumbnailUrl('square')); ?>">
                <span class="file-name"><?php echo $this->escapeHtml($media->displayTitle()); ?>
            </a>
        </div>
        <?php endforeach; ?>
    </div>
    <div class="meta-group">
        <?php echo $cItem->displayInputs(); ?>
    </div>
</div>
