<div id="collecting-section" class="section">
    <p><?php echo sprintf(
        $this->translate('This item was submitted on %s using the form “%s” on the site “%s”.'),
        $this->i18n()->dateFormat($cItem->item()->created(), 'long'),
        $cItem->form()->label(),
        $cItem->form()->site()->link($cItem->form()->site()->title())
    ); ?></p>
    <?php foreach ($cItem->inputs() as $input): ?>
    <div class="property">
        <h4><?php echo $this->escapeHtml($input->prompt()->displayText()); ?></h4>
        <div class="value"><?php echo nl2br($this->escapeHtml($input->displayText())); ?></div>
    </div>
    <?php endforeach; ?>
</div>
